Fixed the ability to pull to refresh data from firebase
zcjhnsn/Boost-ctRL pull request #10
Opened 2019-04-09 06:36 UTC by ntfalcone93

This branch fixes the ability to pull and refresh data from Firebase. It still stores the data it fetches in Realm and then updates the table view.

2019-04-09 06:37 UTC, ntfalcone93 commented on Boost Ctrl/Boost Ctrl/Controller/Matches/MatchesContentViewController.swift
> +        // TODO: I'm not sure why this is crashing on threadGroup.leave() but i'll look into it. For now the code below should work
I want to clean this up before I merge. I'm not sure why it was crashing but I'd rather use the DispatchGroup over nesting the calls.

2019-04-09 06:40 UTC, ntfalcone93 commented on Boost Ctrl/Boost Ctrl/Controller/Matches/MatchesContentViewController.swift
> +        reloadFirebaseData { [weak self] in
I don't think this will cause a retain cycle but I don't know the code well enough to say for sure so I added weak self just in case.

2019-04-09 17:07 UTC, zcjhnsn commented on Boost Ctrl/Boost Ctrl/Controller/Matches/MatchesContentViewController.swift
> +                matchesArray = matchesArrayRLCS
This doesn't quite work right. Try going to the RLRS tab and doing a pull to refresh. The RLRS tab is then populated with RLRS data. If we add a similar line to `loadRLRSData()`, and refresh the RLCS tab, RLRS data is shown.

2019-04-09 17:18 UTC, zcjhnsn commented
The segmented control flow works like this: 

1. The segmented control (`leagueSwitch`) defaults to show RLCS data.
2. `MatchesContentViewController` loads the RLCS data from Realm and populates the view with that data
3. When `leagueSwitch` is switched to RLRS, the content of matches array is changed to the RLRS array. This is why changing tabs updates the view right now. 

Basically, we need a way to make the pull to refresh only work with the current array that is populating the data. Maybe a size check on `matchesArray` since `matchesArray` will contain 4 arrays for RLCS and 2 arrays for RLRS?

2019-04-09 17:19 UTC, zcjhnsn requested changes
See above comment

2019-04-09 17:41 UTC, zcjhnsn commented
I hate using constants, but this seems to work:

```
func reloadFirebaseData(completion: @escaping () -> ()) {
        fetchDataFromFirebase { [weak self] in
			if self?.matchesArray.count == 4 {
				self?.loadRLCSData()
				if let matches = self?.matchesArrayRLCS {
					self?.matchesArray = matches
				}
			} else {
				self?.loadRLRSData()
				if let matches = self?.matchesArrayRLRS {
					self?.matchesArray = matches
				}
			}
			self?.tableView.reloadData()
			print(self?.matchesArray.count)
            print("Refresh RLCS Matches Download: Complete ✅" )
            completion()
        }
}
```

2019-04-11 04:19 UTC, zcjhnsn approved these changes

2019-04-11 04:31 UTC, merged